@startuml

title Provisioning using X.509 device ID cert

participant EIS
participant "openssl-engine-ks"

box KS
participant KS
participant "libiothsm-keygen"
end box

box CS
participant CS
participant "libiothsm-certgen"
end box

participant DPS

EIS -> KS ++: load_key_pair("device_id")
KS -> "libiothsm-keygen" ++: load_key_pair("device_id")
return OK
return OK("key handle")
EIS -> "openssl-engine-ks" ++: load_private_key("key handle")
return openssl::EVP_PKEY

EIS -> CS ++: create_or_load_cert("device_id")
CS -> "libiothsm-certgen" ++: create_or_load_cert("device_id")
return OK(openssl::X509)
return OK(cert PEM)

EIS -> DPS ++: TLS client auth using privkeys's openssl::EVP_PKEY + openssl::X509 from cert PEM
return Provisioning response

@enduml
